refactor: Specify css-loader options (#161)
I think this will make it easier to upgrade `css-loader`, which in turn I think will be necessary in order to upgrade to webpack 5.

At the time of writing, the latest version of `css-loader` that matches `^3.2.0` – and the one used in the bootstrapped userscript, SimonAlling/example-userscript@d1d30ea5 and SimonAlling/better-sweclockers@7381699f, according to `npm why` – is **3.6.0**. I went [here] to check what its default options are, and then I specified them. For some of them, the documented default value isn't obviously correct/sensible:

  * ### `hashPrefix`

    The documented default value is `undefined`, but based on [the source code][hashPrefix], it's actually `""`. That makes much more sense to me too.

  * ### `getLocalIdent`

    The documented default value is `undefined`, but specifying that causes consuming userscripts (e.g. SimonAlling/example-userscript@d1d30ea5) to fail to build with this error:

        TypeError: modulesOptions.getLocalIdent is not a function

  * ### `localIdentRegExp`

    The documented default value is `undefined`, but based on [the source code][localIdentRegExp], it's actually `null`. Specifying `null`, however, causes consuming userscripts (e.g. SimonAlling/example-userscript@d1d30ea5) to fail to build with this error:

        Details:
         * options.modules.localIdentRegExp should be one of these:
           string | RegExp
           Details:
            * options.modules.localIdentRegExp should be a string.
            * options.modules.localIdentRegExp should be an instance of RegExp.

[here]: https://github.com/webpack-contrib/css-loader/tree/v3.6.0
[hashPrefix]: https://github.com/webpack-contrib/css-loader/blob/v3.6.0/src/utils.js#L133
[localIdentRegExp]: https://github.com/webpack-contrib/css-loader/blob/v3.6.0/src/utils.js#L134