build: Upgrade to Jest 27 (#147)
This decreases the number of vulnerabilities according to `npm audit`:

  * **Before:** 40 vulnerabilities (1 low, 8 moderate, 30 high, 1 critical)
  * **After:** 22 vulnerabilities (1 low, 8 moderate, 13 high)

I made the changes like this:

    npm install --save-dev --save-exact jest@27 @types/jest@27 ts-jest@27

Then `npm test` failed with this error:

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string. Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

So I set the test environment to `"jsdom"`.