build: Enable exactOptionalPropertyTypes (#175)
I'm considering introducing [Semantic Versioning for TypeScript Types][semver-ts], which requires `exactOptionalPropertyTypes` (and `noUncheckedIndexedAccess`, which was enabled in #174).

Without `skipLibCheck`, we get this compilation error:

    node_modules/@types/webpack/index.d.ts:2264:23 - error TS2430: Interface 'Options' incorrectly extends interface 'MinifyOptions'.
      Types of property 'sourceMap' are incompatible.
        Type 'boolean | undefined' is not assignable to type 'boolean | SourceMapOptions'.
          Type 'undefined' is not assignable to type 'boolean | SourceMapOptions'.

    2264             interface Options extends UglifyJS.MinifyOptions {
                               ~~~~~~~

Maybe we can disable `skipLibCheck` again in the future, but for now it has to go.

[semver-ts]: https://www.semver-ts.org/#for-package-authors